import BrowseDormsButton from "@/components/BrowseDormsButton";
import Navbar from "@/components/Navbar";
import SignInButton from "@/components/SignInButton";
import VoteButton from "@/components/VoteButton";

export default function Home() {
  return (
    <>
      <Navbar />
      <main className="min-h-screen bg-gradient-to-b from-indigo-50 via-white to-rose-50 px-6 pt-24 pb-10">
        <div className="mx-auto w-full max-w-3xl">

        {/* Hero */}
        <div className="mt-10">
          <div className="inline-flex items-center gap-2 rounded-full border border-indigo-200/70 bg-white/70 px-3 py-1 text-xs font-medium text-indigo-700 shadow-sm">
            <span className="h-2 w-2 rounded-full bg-indigo-500" />
            Columbia University
          </div>

          <h1 className="mt-4 text-4xl font-semibold tracking-tight text-neutral-900">
            Homepage
          </h1>

          <p className="mt-3 max-w-2xl text-neutral-600">
            Browse Columbia dorms. Rate funny captions. Just have fun!
          </p>
        </div>

        {/* Action grid */}
        <div className="mt-10 grid gap-4 md:grid-cols-2">
          {/* Browse */}
          <div className="group flex min-h-[200px] flex-col rounded-3xl border border-neutral-200 bg-white p-6 shadow-sm transition hover:shadow-md">
            <div>
              <h2 className="text-lg font-semibold text-neutral-900">
                Browse dorms
              </h2>
              <p className="mt-1 text-sm text-neutral-600">
                Scroll through a visual catalog of Columbia dorms.
              </p>
            </div>

            <div className="mt-auto">
              <div className="grid grid-cols-2 gap-3">
                <div className="h-10">
                  <BrowseDormsButton />
                </div>
                <div className="h-10 invisible">
                  <div className="h-full w-full" />
                </div>
              </div>
            </div>
          </div>

          {/* Vote */}
          <div className="group flex min-h-[200px] flex-col rounded-3xl border border-neutral-200 bg-white p-6 shadow-sm transition hover:shadow-md">
            <div>
              <h2 className="text-lg font-semibold text-neutral-900">
                Rate captions
              </h2>
              <p className="mt-1 text-sm text-neutral-600">
                Upvote or downvote captions generated by AI.
              </p>
            </div>

            <div className="mt-auto">
              {/* Even button row */}
              <div className="grid grid-cols-2 gap-3">
                <VoteButton />

                <SignInButton />
              </div>
            </div>
          </div>
        </div>

        {/* Minimal footer */}
        <div className="mt-10 text-center text-xs text-neutral-500">
          Built with Next.js + Supabase.
        </div>
        </div>
      </main>
    </>
  );
}